version: '3'
services:
  app:
    image: todo-backend
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/tododb
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
