services:
  frontend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

    debug-helper:
    image: busybox 